-- Eğer tablo yoksa oluştur (zaten varsa bu kısmı atla)
create table if not exists oyunlar (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  isim text not null,
  renk text default '#33ccff',
  html_kodu text not null,
  slug text unique not null,
  is_active boolean default true
);

-- RLS aç (zaten açıksa hata vermez, devam et)
alter table oyunlar enable row level security;

-- Eski policy varsa sil, yeniden oluştur
drop policy if exists "herkes okuyabilir" on oyunlar;
drop policy if exists "herkes yazabilir" on oyunlar;
drop policy if exists "herkes silebilir" on oyunlar;
drop policy if exists "herkes guncelleyebilir" on oyunlar;

create policy "herkes okuyabilir"
  on oyunlar for select using (true);

create policy "herkes yazabilir"
  on oyunlar for insert with check (true);

create policy "herkes silebilir"
  on oyunlar for delete using (true);

create policy "herkes guncelleyebilir"
  on oyunlar for update using (true);
